import { describe, expect, it } from "vitest";
import { existsSync, mkdtempSync, writeFileSync } from "node:fs";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { graph } from "./graph";
import {
  allModelReviews, disagreementsFor, foreignSources, loadModelReviews, MODEL_PANEL, MODEL_REVIEWS_DIR, ModelReviewSchema, panelModel, panelOverview, parseModelReviews, recordSources, type ModelReview,
} from "./model-reviews";

const fable = MODEL_PANEL[0];
const astra = MODEL_PANEL[1];
const base: ModelReview = {
  recordId: "tnbc", model: fable, date: "2026-09-17", confidence: "high", summary: "One paragraph.",
  verdicts: [{ claim: "The record lists five rows.", stance: "supports", note: "Counted.", source: { label: "Wikipedia", url: "https://en.wikipedia.org/wiki/Triple-negative_breast_cancer" } }],
};

describe("model review schema", () => {
  it("accepts a well-formed review and rejects bad stances, dates, ids and empty verdicts", () => {
    expect(ModelReviewSchema.safeParse(base).success).toBe(true);
    expect(ModelReviewSchema.safeParse({ ...base, verdicts: [] }).success).toBe(false);
    expect(ModelReviewSchema.safeParse({ ...base, date: "17/09/2026" }).success).toBe(false);
    expect(ModelReviewSchema.safeParse({ ...base, recordId: "TNBC" }).success).toBe(false);
    expect(ModelReviewSchema.safeParse({ ...base, confidence: "certain" }).success).toBe(false);
    expect(ModelReviewSchema.safeParse({ ...base, verdicts: [{ ...base.verdicts[0], stance: "agrees" }] }).success).toBe(false);
    expect(ModelReviewSchema.safeParse({ ...base, verdicts: [{ ...base.verdicts[0], source: { label: "x", url: "not a url" } }] }).success).toBe(false);
  });

  it("panel table has distinct ids and names, Fable first, and unknown ids fall back to the raw id", () => {
    expect(new Set(MODEL_PANEL.map((m) => m.id)).size).toBe(MODEL_PANEL.length);
    expect(new Set(MODEL_PANEL.map((m) => m.name)).size).toBe(MODEL_PANEL.length);
    expect(MODEL_PANEL.map((m) => m.name)).toContain("Fable");
    expect(MODEL_PANEL.map((m) => m.name)).toContain("Astra");
    expect(panelModel("claude-fable-5-1").name).toBe("Fable");
    expect(panelModel("some-other-model")).toMatchObject({ id: "some-other-model", name: "some-other-model" });
  });
});

describe("disagreement derivation", () => {
  it("surfaces claims where models differ and ignores agreement, case and trailing punctuation", () => {
    const a: ModelReview = { ...base, verdicts: [
      { claim: "The record lists five rows.", stance: "supports", note: "a" },
      { claim: "Urothelial cancer is listed among the record's indications.", stance: "disputes", note: "withdrawn" },
      { claim: "Only Fable says this.", stance: "missing", note: "solo" },
    ] };
    const b: ModelReview = { ...base, model: astra, confidence: "medium", verdicts: [
      { claim: "the record lists five rows", stance: "supports", note: "b" },
      { claim: "Urothelial cancer is listed among the record's indications", stance: "supports", note: "history" },
    ] };
    const d = disagreementsFor([a, b]);
    expect(d).toHaveLength(1);
    expect(d[0].claim).toMatch(/^Urothelial/);
    expect(d[0].positions.map((p) => [p.model.name, p.stance])).toEqual([["Fable", "disputes"], ["Astra", "supports"]]);
    expect(disagreementsFor([a])).toEqual([]);
    expect(disagreementsFor([])).toEqual([]);
  });
});

describe("loader", () => {
  it("returns nothing for records without a file and validates files it reads", () => {
    expect(loadModelReviews("no-such-record")).toEqual([]);
    const dir = mkdtempSync(join(tmpdir(), "nuclide-model-reviews-"));
    writeFileSync(join(dir, "tnbc.json"), JSON.stringify([{ ...base, date: "2026-01-01" }, { ...base, model: astra }]));
    writeFileSync(join(dir, "broken.json"), JSON.stringify([{ ...base, recordId: "broken", confidence: "sure" }]));
    writeFileSync(join(dir, "misfiled.json"), JSON.stringify([base]));
    const list = loadModelReviews("tnbc", dir);
    expect(list.map((r) => r.date)).toEqual(["2026-09-17", "2026-01-01"]);
    expect(() => loadModelReviews("broken", dir)).toThrow(/broken\.json/);
    expect(() => loadModelReviews("misfiled", dir)).toThrow(/wrong file/);
    expect(() => parseModelReviews("x", "{}")).toThrow();
  });

  it("every shipped file validates, names a real record, cites only that record's own sources, and marks examples", () => {
    const g = graph();
    const all = allModelReviews();
    // public/reviews/models/ is generated by scripts/model-reviews.ts (live LLM calls) or hand-written
    // examples; this fork ships neither for the new corpus yet, so an empty set is valid and the file
    // checks below simply have nothing to iterate over.
    for (const [recordId, list] of all) {
      const e = g.get(recordId);
      expect(e, `record ${recordId} exists`).toBeDefined();
      for (const r of list) {
        expect(r.recordId).toBe(recordId);
        expect(foreignSources(r, e!), `${recordId} / ${r.model.name} sources`).toEqual([]);
        expect(r.summary.includes("—"), "no em-dashes").toBe(false);
        for (const v of r.verdicts) expect(v.source, `${recordId} / ${r.model.name}: "${v.claim}" has a source`).toBeDefined();
        // Live reviews (written by scripts/model-reviews.ts with a key) must carry a model and a date; examples must say so.
        if (r.example) expect(r.example).toBe(true);
        else { expect(r.model.id).toBeTruthy(); expect(r.date).toMatch(/^\d{4}-\d{2}-\d{2}/); }
      }
    }
  });

  // Deleted: this test asserted the exact shape of hand-written example model-review files for the
  // old oncology records "tnbc" and "sacituzumab-govitecan" (including a specific withdrawal/
  // re-approval regulatory history invented for that demo). Those records and their example review
  // files do not exist in the Nuclide corpus (see docs/FORK-NOTES.md); there is no equivalent
  // fixture to substitute without inventing facts, so the demo-specific assertions are removed
  // rather than faked.

  it("record sources include links, Wikipedia, guideline and regulatory URLs", () => {
    const g = graph();
    const urls = recordSources(g.must("breast-her2-positive")).map((s) => s.url);
    expect(urls).toContain("https://en.wikipedia.org/wiki/HER2-positive_breast_cancer");
    expect(urls.some((u) => u.includes("nccn.org"))).toBe(true);
    expect(new Set(urls).size).toBe(urls.length);
    const durva = recordSources(g.must("durvalumab")).map((s) => s.url);
    expect(durva.some((u) => u.startsWith("https://www.fda.gov/"))).toBe(true);
  });

  it("panel overview counts records per model and puts disagreements first", () => {
    const o = panelOverview();
    expect(o.models[0].onPanel).toBe(true);
    for (let i = 1; i < o.records.length; i++) expect(o.records[i - 1].disagreements).toBeGreaterThanOrEqual(o.records[i].disagreements);
    // public/reviews/models/ is generated (see comment above); this fork does not ship any files for
    // the new corpus yet, so the per-record counts below only apply once some exist.
    if (!existsSync(MODEL_REVIEWS_DIR)) return;
    const fableRow = o.models.find((m) => m.id === fable.id);
    expect(fableRow?.records).toBeGreaterThanOrEqual(2);
  });
});
