/** Site information architecture: five groups, each with a landing page and its pages. Used by the header, footer, landing pages, and home. */
/** `regions`: show only when the reader has chosen one of these countries (Global view shows everything). */
export type NavItem = { href: string; label: string; blurb: string; regions?: Array<"US" | "EU" | "UK" | "JP" | "CN" | "AU" | "IN"> };
/** `short` is an optional shorter label for the desktop header bar only; the drawer, footer and landing pages use `label`. */
export type NavGroup = { id: string; label: string; short?: string; href: string; blurb: string; items: NavItem[] };

export const NAV_GROUPS: NavGroup[] = [
  {
    id: "find", label: "Start here", href: "/find/", blurb: "Begin from an isotope, an agent, a target or a question, and follow the links in any direction.",
    items: [
      { href: "/opportunities/", label: "Opportunities", blurb: "Where a clinical decision cannot be made today and a radiopharmaceutical might settle it, each with the evidence read and the study that would test it." },
      { href: "/explore/", label: "Explore", blurb: "Pick an indication, switch kind, get a ranked and sortable list." },
      { href: "/search/", label: "Search", blurb: "Word and concept search side by side, each result explaining why it matched." },
      { href: "/path/", label: "Path finder", blurb: "How any two objects are related: shortest routes with every relationship named." },
      { href: "/compare/", label: "Compare", blurb: "Up to five agents, isotopes, targets, trials or indications side by side, differences highlighted." },
      { href: "/pivot/", label: "Landscape grid", blurb: "Count agents, trials or technologies by indication, target, isotope or company in one grid." },
      { href: "/timeline/", label: "Timeline", blurb: "Scrub through the years: approvals, trials and practice as it stood." },
      { href: "/query/", label: "Query", blurb: "Build a graph query and get a table." },
      { href: "/graph/", label: "Graph explorer", blurb: "Navigate the knowledge graph visually." },
      { href: "/saved/", label: "Saved", blurb: "Your saved table views and watched pages, with what changed since you looked. Stored in your browser only." },
    ],
  },
  {
    id: "map", label: "Isotopes & agents", short: "The field", href: "/map/", blurb: "Every radionuclide, every labelled molecule, every target, indication and trial. One page each, plain English first.",
    items: [
      { href: "/isotopes/", label: "Isotopes", blurb: "Half-life, what it emits, how it is made, how tight supply is." },
      { href: "/drugs/", label: "Agents", blurb: "Therapeutic radiopharmaceuticals and diagnostic tracers, approved and in trials." },
      { href: "/targets/", label: "Targets", blurb: "PSMA, SSTR2, FAP and the rest: what the ligand is aimed at." },
      { href: "/technologies/", label: "Technologies", blurb: "Chelators, generators, production routes, scanners, dosimetry." },
      { href: "/indications/", label: "Indications", blurb: "What these agents are used for, in oncology, neurology, cardiology and infection." },
      { href: "/fronts/", label: "Fronts", blurb: "The areas of the field, from molecular imaging to alpha therapy and supply." },
      { href: "/trials/", label: "Trials", blurb: "Landmark and current trials, with results where they have reported." },
      { href: "/pairings/", label: "Pairings", blurb: "Theranostic pairs, combinations, sequences and the pairs to avoid." },
      { href: "/roadmaps/", label: "Roadmaps", blurb: "History to horizon for each part of the field." },
      { href: "/dependencies/", label: "Dependency map", blurb: "What each technology cannot exist without, drawn in layers." },
      { href: "/molecules/", label: "Molecule gallery", blurb: "Every agent with a 3D structure, filterable by modality, isotope and target." },
      { href: "/bottlenecks/", label: "Bottlenecks", blurb: "The constraints holding the field back, and the ideas that could break each one." },
      { href: "/ideas/", label: "Ideas", blurb: "Hypotheses and fixes, each with a proposed test." },
      { href: "/terms/", label: "Glossary", blurb: "Physics, chemistry, dosimetry, safety and regulation, in plain words." },
      { href: "/collections/", label: "Collections", blurb: "The open databases and standards the field runs on." },
      { href: "/pathways/", label: "Pathways", blurb: "The biology behind the targets, drawn and explained." },
    ],
  },
  {
    id: "intel", label: "News & evidence", href: "/intel/", blurb: "What is happening and how strong the evidence is: readouts, approvals, supply, failures and the money.",
    items: [
      { href: "/supply/", label: "Isotope supply", blurb: "Who makes Lu-177, Ac-225, Mo-99 and Pb-212, and how tight each is." },
      { href: "/evidence/", label: "Evidence", blurb: "Every trial ranked by evidence strength, endpoints as people out of 100." },
      { href: "/explained/", label: "Trials in plain words", blurb: "Every trial result as people out of 100, medians explained, surrogate endpoints flagged." },
      { href: "/key-papers/", label: "Key papers", blurb: "The papers that changed practice, each explained: what it found and what to be careful about." },
      { href: "/journals/", label: "Journals", blurb: "Where the evidence is published: scope, access model and the papers each venue carried." },
      { href: "/calendar/", label: "Readout calendar", blurb: "Decisions, readouts, advisory committees, congresses." },
      { href: "/catalysts/", label: "Catalyst calendar", blurb: "Regulatory decisions, expected readouts, filings and deal closings by company." },
      { href: "/regulatory/", label: "Regulatory timeline", blurb: "Every dated filing, approval, CRL and label change." },
      { href: "/deals/", label: "Deals and licences", blurb: "Who bought or licensed what, for how much." },
      { href: "/failures/", label: "Failure museum", blurb: "What did not work, and the lesson." },
      { href: "/trial-designs/", label: "Trial design picker", blurb: "Every trial design as a card: when to use it, a worked example and its main risk." },
      { href: "/preprints/", label: "Preprint tracker", blurb: "Recent preprints per target, agent and technology, and which have since been published." },
      { href: "/papers/", label: "Publishing trends", blurb: "Fastest-growing topics in the literature, refreshed weekly from Europe PMC." },
      { href: "/pulse/", label: "Research pulse", blurb: "What the leading journals, regulators and news sources are saying this month." },
      { href: "/changelog/", label: "Changelog", blurb: "What changed in Nuclide, and when." },
      { href: "/status/", label: "Data currency", blurb: "When each automated feed last ran, what is stale, and the incident log." },
      { href: "/freshness/", label: "Freshness", blurb: "How old is too old for each kind of record, and what is past due." },
      { href: "/history/", label: "Recent changes", blurb: "What changed on which record, field by field, from the git history." },
      { href: "/audit/", label: "Audit", blurb: "Staleness, contradictions and registry mismatches, recomputed each build." },
      { href: "/corrections/", label: "Corrections", blurb: "Every factual correction, what was wrong and how it was found." },
    ],
  },
  {
    id: "who", label: "Institutions & people", short: "Who's who", href: "/institutions/", blurb: "The theranostic centres, the isotope producers, the companies and the people behind them.",
    items: [
      { href: "/institutions/", label: "Institutions", blurb: "Theranostic centres, university hospitals, regulators and agencies, mapped." },
      { href: "/people/", label: "People", blurb: "The physicians, physicists and chemists doing the work." },
      { href: "/companies/", label: "Companies", blurb: "Radiopharma, isotope producers, generator and scanner makers." },
      { href: "/leadership/", label: "Trial leadership", blurb: "Who led the pivotal trials." },
      { href: "/manufacturing/", label: "Manufacturing map", blurb: "Where isotopes are produced and where agents are labelled and released." },
      { href: "/sponsors/", label: "Trial sponsors", blurb: "Who runs the most phase 2 and 3 trials, from the registry and the corpus." },
    ],
  },
  {
    id: "learn", label: "Learn & contribute", href: "/learn/", blurb: "Curated paths through the material, how the site works, and how to make it better.",
    items: [
      { href: "/about/", label: "About & methodology", blurb: "Rules for facts, ranking formulas, licence." },
      { href: "/roadmap/", label: "Roadmap", blurb: "Corpus health, every idea by status, and how Nuclide expands and stays current." },
      { href: "/gaps/", label: "Gaps to fill", blurb: "Objects and fields that need work." },
      { href: "/review/", label: "Review queue", blurb: "Which pages most need a named reviewer." },
      { href: "/reviewers/", label: "Reviewer roster", blurb: "Who has signed off pages, with declared conflicts of interest." },
      { href: "/contributors/", label: "Contributors", blurb: "Everyone who wrote or reviewed records, from the repository history." },
      { href: "/newsletter/", label: "Weekly issue", blurb: "What changed, regulatory events, upcoming readouts. No tracking." },
      { href: "/suggest/", label: "Suggest an edit", blurb: "Propose a correction; organisations can edit their own records." },
      { href: "/eval/", label: "Open evaluation", blurb: "Questions, a rubric and a public leaderboard." },
      { href: "/schema/", label: "Data dictionary", blurb: "Every kind, every field, its type and meaning, with a real example per kind." },
      { href: "/build/", label: "Build on Nuclide", blurb: "Recipes, OpenAPI spec, TypeScript types and the MCP server." },
      { href: "/api/", label: "Open API", blurb: "The corpus as JSON." },
      { href: "/data-sources/", label: "Open data", blurb: "Every open database Nuclide pulls from, with licences and cadence." },
      { href: "/open-tools/", label: "Open tools", blurb: "Open-source viewers, planners and pipelines you can use or build on." },
      { href: "https://github.com/casadesante/Nuclide", label: "GitHub", blurb: "Code and data. Propose changes through the issue forms." },
    ],
  },
];
