import type { EntityInput } from "@/lib/schema";

export const newTargets: EntityInput[] = [
  {
    id: "caix",
    kind: "target",
    name: "CAIX (carbonic anhydrase IX)",
    aka: ["CA9", "G250 antigen", "MN antigen"],
    symbol: "CA9",
    tldr: "A protein that clear cell kidney cancer makes almost all the time because of a gene fault. It helps the tumour survive in low-oxygen conditions, and antibodies that stick to it can be used to find or treat the cancer.",
    summary: "Carbonic anhydrase IX is a transmembrane enzyme with an extracellular catalytic domain that helps regulate intracellular and extracellular pH, allowing tumour cells to survive an acidic, hypoxic microenvironment. Its expression is switched on by the HIF-1 transcription factor: in clear cell renal cell carcinoma (ccRCC), loss-of-function mutation or deletion of the VHL tumour-suppressor gene (found in roughly 75-95% of ccRCC cases) leaves HIF-1α constitutively active even without hypoxia, so CAIX is expressed diffusely and strongly on almost all ccRCC cells, in contrast to normal kidney, which does not express it.\n\nThis expression pattern (near-ubiquitous in ccRCC, essentially absent in normal renal parenchyma and in non-clear-cell kidney tumours) is what makes CAIX attractive: it is a differential diagnostic marker for ccRCC as well as a therapeutic target. The chimeric monoclonal antibody girentuximab (cG250) binds a conformational epitope on the catalytic domain, internalises via clathrin-coated vesicles and recycles rather than being degraded, giving long intracellular retention. Because girentuximab is a full antibody, tumour-to-background contrast builds slowly and imaging is typically read several days after injection.\n\nAs a target, CAIX's strength is its consistency and specificity in ccRCC; its weakness for antibody-based approaches is slow pharmacokinetics (days, not hours) and the fact that HIF-2α-driven, VHL-independent disease later in progression can show falling CAIX expression, which has been linked to worse prognosis. Small-molecule and peptide CAIX ligands (for example 68Ga-DPI-4452) have since been developed to give same-day imaging with high tumour-to-background contrast.",
    targetClass: "enzyme",
    biology: "A transmembrane carbonic anhydrase whose extracellular catalytic domain hydrates CO2 to bicarbonate and protons, helping tumour cells regulate pH and survive hypoxia. Its expression is switched on by the HIF-1 pathway, so it is expressed at very high, uniform density in VHL-mutant clear cell renal cell carcinoma while normal kidney does not express it.",
    whereFound: [
      "Clear cell renal cell carcinoma: overexpressed in >90-95% of cases, driven by VHL/HIF-1 pathway loss",
      "Normal kidney parenchyma: essentially absent",
      "Some hypoxic non-renal tumours (expression follows tumour hypoxia rather than a fixed tissue pattern)",
      "Normal gastrointestinal tract: low-level physiological expression"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "PMC review: CAIX in renal cell carcinoma, implications for imaging and therapy", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7582814/" },
      { label: "PMC: application of CAIX-targeted radiotracers in ccRCC", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC12976585/" },
      { label: "Spandidos: monoclonal antibody G250 targeting CAIX, internalisation and epitope", url: "https://www.spandidos-publications.com/10.3892/ijo.2014.2658/download" },
      { label: "JNM editorial: kick-starting molecular theranostics in renal cell carcinoma (VHL/HIF, girentuximab, 68Ga-DPI-4452)", url: "https://jnm.snmjournals.org/content/65/5/744" }
    ],
    related: ["girentuximab-zr89", "caix-pet", "rcc", "hif-vhl", "idea-caix-theranostics", "nct06750419", "nct07197580", "telix"],
    tags: ["renal cell carcinoma", "hypoxia", "antibody target"],
  },
  {
    id: "nis-symporter",
    kind: "target",
    name: "NIS (sodium-iodide symporter)",
    aka: ["Sodium/iodide cotransporter", "SLC5A5"],
    symbol: "SLC5A5",
    tldr: "A protein in the thyroid that pulls iodine out of the blood to make thyroid hormone. It is the reason radioactive iodine can find and treat thyroid cancer almost anywhere in the body.",
    summary: "NIS is a 13-transmembrane-domain glycoprotein on the basolateral membrane of thyroid follicular cells that actively co-transports two sodium ions with one iodide ion, using the electrochemical sodium gradient generated by Na+/K+-ATPase, as the first step of thyroid hormone synthesis. Its expression in the thyroid is driven by thyroid-stimulating hormone (TSH) acting through the cAMP pathway, which is why thyroid-stimulating hormone withdrawal or recombinant human TSH (thyrotropin alfa) is used clinically to maximise iodide uptake before radioiodine scanning or therapy.\n\nMore than 70% of differentiated (papillary and follicular) thyroid cancers retain enough NIS expression to concentrate iodide, which is the biological basis of whole-body radioiodine scanning and I-131 therapy for remnant ablation and metastatic disease. NIS is also expressed, at lower levels, in several extrathyroidal tissues: salivary glands, gastric mucosa, lactating breast, lacrimal glands, choroid plexus and placenta. Uptake in salivary glands and stomach is well below thyroid levels and the absorbed dose in these tissues is small relative to the thyroid, but it is still the mechanism behind the sialadenitis (dry mouth, taste change) and, less often, gastritis seen after high-activity I-131 therapy.\n\nAs a target, NIS is close to ideal for differentiated thyroid cancer: high density, non-internalising simple ion transport, and near-total tissue restriction outside a few low-uptake sites. Its main practical limitation is that a minority of thyroid cancers dedifferentiate and lose NIS expression (radioiodine-refractory disease), and normal-tissue uptake in salivary gland and stomach still causes most of the non-thyroid toxicity of I-131 therapy.",
    targetClass: "other",
    biology: "A basolateral membrane glycoprotein that actively co-transports two sodium ions with one iodide ion into thyroid follicular cells, the first step of thyroid hormone synthesis, driven by TSH via the cAMP pathway. Because most differentiated thyroid cancer retains this transporter, it is the biological basis for diagnostic and therapeutic use of radioactive iodine.",
    whereFound: [
      "Thyroid follicular cells: high, TSH-driven expression; basis of normal thyroid hormone synthesis",
      "Differentiated thyroid cancer: retained in >70% of papillary and follicular carcinomas",
      "Salivary gland striated ducts: moderate expression, clinically relevant because of I-131 sialadenitis",
      "Gastric mucosa (basolateral): moderate expression, secretes iodide into gastric juice",
      "Lactating mammary gland, lacrimal gland, choroid plexus, placenta: lower-level physiological expression"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "PMC: modulation of NIS expression in salivary gland tissue and I-131 uptake", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3752512/" },
      { label: "PMC: the sodium iodide symporter (NIS) - regulation and approaches to therapy", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3408573/" },
      { label: "PMC: sodium/iodide symporter - molecular physiology and preclinical applications (tissue distribution table)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5739519/" },
      { label: "MedlinePlus Genetics: SLC5A5 gene", url: "https://medlineplus.gov/genetics/gene/slc5a5/" }
    ],
    related: ["radioactive-iodine", "radioiodine-therapy", "thyroid", "thyrotropin-alfa", "radioiodine-term"],
    tags: ["thyroid", "ion transporter", "theranostics"],
  },
  {
    id: "norepinephrine-transporter",
    kind: "target",
    name: "Norepinephrine transporter (NET)",
    aka: ["NET", "Noradrenaline transporter"],
    symbol: "SLC6A2",
    tldr: "A protein on nerve cells and adrenal-type tumour cells that pulls noradrenaline back inside after it has been released. A radioactive drug called MIBG looks and acts enough like noradrenaline that this same protein carries it into neuroblastoma and phaeochromocytoma cells, so doctors can see or treat the tumour.",
    summary: "The norepinephrine transporter is a 12-transmembrane-domain protein of presynaptic sympathetic neurons and adrenal medullary chromaffin cells that terminates noradrenergic signalling by taking norepinephrine back into the cell (uptake-1), an active, sodium- and chloride-dependent, ATP-driven process roughly 50-fold more efficient than passive diffusion. Once inside, norepinephrine (and NET's synthetic analogue metaiodobenzylguanidine, MIBG) can be stored in secretory vesicles via the vesicular monoamine transporters (VMAT1/2) or remain in the cytoplasm.\n\nTumours that arise from sympathetic neural crest precursors - neuroblastoma, phaeochromocytoma and paraganglioma - retain NET expression at high frequency (around 90% of neuroblastomas are NET-positive), and expression correlates with MIBG avidity on imaging. Radioiodinated MIBG (123I for diagnosis, 131I for therapy) is taken up through NET, giving both a diagnostic scan and, at therapeutic activities, a targeted radiotherapy. Other transporters (OCT1-3, MATE1/2-K) contribute to non-specific uptake into liver, salivary gland and heart and to renal clearance, and drugs that block NET (tricyclic antidepressants, some stimulants) must be stopped before MIBG scanning or therapy because they blunt tumour uptake.\n\nAs a target, NET's strength is high, tumour-restricted expression in an otherwise hard-to-image tumour family, plus intracellular retention via VMAT once inside the cell. Its main limitations are heterogeneous expression (MYCN-amplified, poorly differentiated neuroblastomas tend to have lower NET expression and are less MIBG-avid) and competition from other transporters that reduce specificity and complicate dosimetry.",
    targetClass: "other",
    biology: "A presynaptic membrane transporter that takes norepinephrine back into sympathetic neurons and adrenal chromaffin cells after release, an active sodium- and chloride-dependent process. Tumours arising from sympathetic neural crest precursors (neuroblastoma, phaeochromocytoma, paraganglioma) retain this transporter at high frequency, allowing the norepinephrine analogue MIBG to be carried into tumour cells for imaging and therapy.",
    whereFound: [
      "Neuroblastoma: NET-positive in roughly 90% of tumours; MYCN-amplified tumours tend to have lower expression",
      "Phaeochromocytoma and paraganglioma: NET expressed in chromaffin-derived tumour cells, uptake reinforced by VMAT storage",
      "Normal sympathetic nerve terminals and adrenal medulla: physiological expression"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "DMD: clinical applications and roles of transporters in disposition, tumour targeting and tissue toxicity of MIBG", url: "https://dmd.aspetjournals.org/content/50/9/1218" },
      { label: "JNM (SNMMI supplement): norepinephrine transporter as a target for imaging and therapy", url: "https://jnm.snmjournals.org/content/58/Supplement_2/39S" },
      { label: "PMC: 'Nothing but NET' - NET expression and efficacy of 131I-MIBG therapy", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4237663/" }
    ],
    related: ["i131-mibg", "iobenguane-i-131", "mibg-theranostics", "pheochromocytoma-paraganglioma", "neuroblastoma", "neuroblastoma-high-risk", "metastatic-ppgl", "hereditary-ppgl", "idea-mfbg-pet-replaces-mibg", "nct04724369", "paper-pryma-high-specific-activity-i131-mibg-ppgl-jnm-2019"],
    tags: ["neuroendocrine", "paediatric", "transporter"],
  },
  {
    id: "amyloid-beta",
    kind: "target",
    name: "Amyloid beta plaques",
    aka: ["Aβ", "beta-amyloid neuritic plaques"],
    tldr: "Sticky clumps of protein that build up in the brain in Alzheimer's disease. PET scans using tracers that bind these clumps can show a doctor how much amyloid is present, well before it would show up on a brain biopsy.",
    summary: "Amyloid beta is a peptide, cleaved from the amyloid precursor protein, that misfolds and aggregates into extracellular neuritic plaques, one of the two neuropathological hallmarks of Alzheimer's disease (the other being tau neurofibrillary tangles). PET tracers such as 18F-florbetapir bind fibrillar amyloid aggregates with nanomolar affinity (Kd approximately 3.7 nM for florbetapir) and do not appreciably bind tau, so they read out plaque burden rather than tangle burden.\n\nFlorbetapir (Amyvid) was FDA-approved in 2012 for PET imaging to estimate beta-amyloid neuritic plaque density in adults with cognitive impairment being evaluated for Alzheimer's disease; its label was updated in June 2025 to add selection of patients for amyloid-targeting therapy, reflecting the arrival of anti-amyloid antibody drugs whose eligibility and monitoring depend on amyloid PET or blood biomarkers. Other approved 18F amyloid tracers include florbetaben (Neuraceq) and flutemetamol (Vizamyl); all three are stilbene or benzothiazole derivatives related to the original 11C-Pittsburgh compound B.\n\nAs an imaging target, amyloid's strength is that a negative scan has high negative predictive value (sparse or no plaque makes an Alzheimer's diagnosis unlikely), which is clinically decisive. Its main limitation is specificity for a diagnosis: a positive scan indicates plaque is present but this can also occur in cognitively normal older adults and in other neurodegenerative conditions, so a positive result does not by itself confirm Alzheimer's disease, and none of the approved tracers is validated to monitor treatment response or to predict conversion to dementia.",
    targetClass: "other",
    biology: "A peptide cleaved from the amyloid precursor protein that misfolds and aggregates into extracellular neuritic plaques, one of the two defining pathologies of Alzheimer's disease. PET tracers bind fibrillar amyloid aggregates with high affinity, giving an in-vivo readout of plaque burden that was previously only obtainable at autopsy.",
    whereFound: [
      "Alzheimer's disease: neuritic plaques throughout association cortex; presence and density scored on amyloid PET",
      "Cognitively normal older adults: a minority show plaque on amyloid PET without dementia",
      "Cerebral amyloid angiopathy and some other neurodegenerative conditions: variable vascular and parenchymal amyloid"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "FDA label: Amyvid (florbetapir F 18 injection)", url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2012/202008s000lbl.pdf" },
      { label: "Eli Lilly: FDA approves updated Amyvid label for amyloid-targeting therapy selection (25 June 2025)", url: "https://investor.lilly.com/news-releases/news-release-details/fda-approves-updated-label-lillys-amyvid-florbetapir-f-18" },
      { label: "PMC: the role of amyloid PET in imaging neurodegenerative disorders", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC9165727/" },
      { label: "CMS national coverage determination memo: beta-amyloid PET in dementia", url: "https://www.cms.gov/medicare-coverage-database/view/ncacal-decision-memo.aspx?proposed=N&NCAId=265" }
    ],
    related: ["tau-protein"],
    tags: ["neurology", "Alzheimer's disease", "protein aggregate"],
  },
  {
    id: "tau-protein",
    kind: "target",
    name: "Tau protein (neurofibrillary tangles)",
    aka: ["PHF-tau", "aggregated tau", "NFTs"],
    tldr: "A protein that normally helps hold nerve cells together but, in Alzheimer's disease, twists into tangles inside the cells. A PET tracer called flortaucipir binds these tangles so doctors can see how far the disease has spread in the brain.",
    summary: "Tau is a microtubule-associated protein that, in Alzheimer's disease, becomes abnormally hyperphosphorylated and aggregates intracellularly into paired helical filaments that form neurofibrillary tangles (NFTs) - one of the two pathologies (with amyloid beta plaques) required for a neuropathological diagnosis of Alzheimer's disease. Tangles accumulate and spread through the brain in a stereotyped anatomical sequence (Braak staging), which is why tau PET, unlike amyloid PET, can track disease stage and distribution rather than simple positive/negative status.\n\nFlortaucipir F18 (Tauvid) binds aggregated PHF-tau with a dissociation constant of 0.57 nM in vitro and shows negligible binding to beta-amyloid, so it reports tangle pathology specifically. It was FDA-approved in May 2020, the first and to date only approved tau PET tracer, for estimating the density and distribution of NFTs in adults with cognitive impairment being evaluated for Alzheimer's disease; it is explicitly not indicated for chronic traumatic encephalopathy, because non-Alzheimer's tauopathies show different tau conformations that the tracer does not reliably detect. Some off-target binding to monoamine oxidase A/B occurs, seen in the choroid plexus, striatum and brainstem, and is excluded from image interpretation.\n\nAs a target, tau's strength is that its regional distribution tracks clinical stage and correlates better with cognitive decline than amyloid burden does. Its main limitation is that flortaucipir's sensitivity is lower in earlier-stage disease (the pivotal studies enrolled mostly terminally ill patients with advanced NFT pathology), and it cannot distinguish Alzheimer's tau from other tauopathies.",
    targetClass: "other",
    biology: "A microtubule-associated protein that becomes hyperphosphorylated and aggregates intracellularly into paired helical filaments forming neurofibrillary tangles, the second defining pathology of Alzheimer's disease. Tangles spread through the brain in a stereotyped anatomical sequence that correlates with clinical stage, distinguishing tau imaging from the simple positive/negative readout of amyloid imaging.",
    whereFound: [
      "Alzheimer's disease: neurofibrillary tangles accumulate in a stereotyped pattern (Braak staging), correlating with cognitive impairment stage",
      "Other tauopathies (progressive supranuclear palsy, Pick's disease, chronic traumatic encephalopathy): different tau conformations, not reliably detected by flortaucipir"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "FDA label: Tauvid (flortaucipir F 18 injection)", url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2024/212123s031lbl.pdf" },
      { label: "FDA integrated review, NDA 212123 (mechanism of action, pivotal trial data)", url: "https://www.accessdata.fda.gov/drugsatfda_docs/nda/2020/212123Orig1s000IntegratedR.pdf" },
      { label: "PMC: Tauvid, the first FDA-approved PET tracer for imaging tau pathology in Alzheimer's disease", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7911942/" },
      { label: "Eli Lilly: FDA approval of Tauvid (28 May 2020)", url: "https://investor.lilly.com/node/43256/pdf" }
    ],
    related: ["amyloid-beta"],
    tags: ["neurology", "Alzheimer's disease", "protein aggregate"],
  },
  {
    id: "dopamine-transporter",
    kind: "target",
    name: "Dopamine transporter (DAT)",
    aka: ["DAT"],
    symbol: "SLC6A3",
    tldr: "A protein on the ends of brain cells that make dopamine, which recycles the dopamine after it has done its job. A scan using a tracer that sticks to this protein can show whether those brain cells are dying, which happens in Parkinson's disease.",
    summary: "The dopamine transporter sits on the axon terminals of presynaptic nigrostriatal dopaminergic neurons, which project from the substantia nigra to the striatum (caudate and putamen), and terminates dopaminergic signalling by taking dopamine back into the neuron after release. Because DAT density on the neuron surface tracks the number of intact nigrostriatal terminals, loss of DAT signal on imaging is a marker of neurodegeneration rather than a direct marker of disease-specific pathology.\n\nIoflupane I-123 (DaTscan/DATSCAN), a radioiodinated cocaine analogue, binds reversibly to DAT (Ki approximately 0.62 nM) and is imaged by SPECT 3-6 hours after injection, concentrating in the striatum in proportion to transporter density. It is FDA- and EMA-approved as an adjunct for striatal DAT visualisation in adults with suspected parkinsonian syndromes and suspected dementia with Lewy bodies, chiefly to help distinguish essential tremor (normal DAT scan) from Parkinsonian syndromes (reduced striatal DAT), and probable dementia with Lewy bodies from Alzheimer's disease.\n\nAs a target, DAT's strength is a clean anatomical readout (striatal uptake) that reliably separates presynaptic neurodegeneration from tremor of other causes. Its main limitation is lack of specificity between the parkinsonian syndromes themselves: DaTscan cannot distinguish idiopathic Parkinson's disease from multiple system atrophy or progressive supranuclear palsy, since all three cause nigrostriatal terminal loss. A range of common drugs (stimulants, some antidepressants, benztropine) bind DAT with high affinity and can interfere with image interpretation, so they typically need to be stopped before scanning.",
    targetClass: "other",
    biology: "A presynaptic membrane transporter on nigrostriatal dopaminergic neuron terminals that recycles dopamine after synaptic release. Its density in the striatum reflects the number of intact dopaminergic terminals, so loss of transporter signal is a marker of the neurodegeneration that occurs in Parkinsonian syndromes and dementia with Lewy bodies.",
    whereFound: [
      "Substantia nigra pars compacta neuron terminals in the striatum: high physiological expression, lost with nigrostriatal degeneration",
      "Parkinson's disease, multiple system atrophy, progressive supranuclear palsy: reduced striatal DAT signal (not distinguishable from each other by DAT imaging alone)",
      "Essential tremor and dementia unrelated to Lewy body disease: normal DAT signal, used to rule out parkinsonian degeneration"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "FDA label: DATSCAN (ioflupane I 123 injection)", url: "https://www.accessdata.fda.gov/drugsatfda_docs/label/2022/022454s010lbl.pdf" },
      { label: "FDA medical review, NDA 022454 (mechanism of action)", url: "https://www.accessdata.fda.gov/drugsatfda_docs/nda/2011/022454sOrig1s000MedR.pdf" },
      { label: "PMC: clinical utility of dopamine transporter SPECT imaging", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3812862/" }
    ],
    related: [],
    tags: ["neurology", "Parkinson's disease", "transporter"],
  },
  {
    id: "bone-hydroxyapatite",
    kind: "target",
    name: "Bone mineral (hydroxyapatite)",
    aka: ["Hydroxyapatite", "bone mineral matrix"],
    tldr: "The hard mineral that makes up bone. Certain radioactive drugs stick to this mineral wherever bone is being actively rebuilt, which is how bone scans find fractures, infection and cancer that has spread to bone, and how some treatments deliver radiation straight to bone metastases.",
    summary: "Bone is a composite of collagen protein and hydroxyapatite, a crystalline calcium phosphate mineral (Ca5(PO4)3OH). Bisphosphonates - and the older diphosphonates such as methylene diphosphonate (MDP) and hydroxymethylene diphosphonate (HDP/HMDP) - bind hydroxyapatite with high affinity through a P-C-P backbone that chelates surface calcium ions in a bidentate arrangement; when labelled with technetium-99m, the resulting Tc-99m-MDP or Tc-99m-HDP complex accumulates on bone in proportion to local blood flow and osteoblastic activity (new bone formation provides more, smaller hydroxyapatite crystals with greater surface area for binding), which is the basis of conventional bone scintigraphy.\n\nA related but chemically distinct mechanism is direct ionic exchange: 18F-fluoride ions substitute for hydroxyl groups in the hydroxyapatite lattice to form fluoroapatite, giving even faster, higher-contrast bone-turnover imaging on PET than Tc-99m bone scans. On the therapy side, the same hydroxyapatite affinity is exploited by bone-seeking radionuclide therapies: samarium-153 lexidronam (a Sm-153-EDTMP bisphosphonate complex) and radium-223 dichloride (a calcium mimetic incorporated directly into the mineral at sites of osteoblastic activity) both concentrate in areas of high bone turnover, including osteoblastic bone metastases, to deliver localised radiation for pain palliation or, for radium-223, a survival benefit in castration-resistant prostate cancer with bone metastases.\n\nAs a target, hydroxyapatite's strength is that bone-turnover tracers and therapies go wherever remodelling is happening, with no receptor saturation or internalisation step required (bone-seeking agents work by chemisorption or ionic exchange, not receptor binding). Its central weakness is a lack of disease specificity: fractures, arthritis, Paget's disease and infection all increase osteoblastic activity and light up alongside malignancy, so bone scans are sensitive but not specific, and specificity depends entirely on the clinical and radiological context.",
    targetClass: "other",
    biology: "The crystalline calcium phosphate mineral phase of bone, bound to a collagen matrix. Bisphosphonates and fluoride ions bind or exchange with this mineral at sites of active bone turnover through chemisorption or ionic substitution respectively, concentrating radiotracers or radionuclide therapy wherever bone remodelling, including reactive new bone at metastases, is occurring.",
    whereFound: [
      "Sites of active bone remodelling generally: fractures, degenerative and inflammatory bone disease, Paget's disease, infection",
      "Osteoblastic bone metastases (prostate, breast and other cancers): increased uptake reflecting reactive new bone formation",
      "Normal growing skeleton: high uptake at epiphyseal growth plates and osteochondral junctions"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "StatPearls: bone scan (mechanism of Tc-99m MDP/HDP binding to hydroxyapatite)", url: "https://www.ncbi.nlm.nih.gov/books/NBK531486/" },
      { label: "MDPI: bisphosphonates as radiopharmaceuticals - DOTAZOL review of bone-targeting chemistry", url: "https://www.mdpi.com/1422-0067/25/1/462" },
      { label: "Applied Radiation and Isotopes review: targeted delivery to bone using bisphosphonate ligands", url: "https://ame.nd.edu/research-legacy/faculty-research-labs/rroeder/publications/publication-pdf/2016%20ADDR%20Cole.pdf" },
      { label: "JNM: kinetics of bone-seeking radiotracers (Tc-99m-diphosphonate vs 18F-fluoride)", url: "https://jnm.snmjournals.org/content/jnumed/early/2013/03/11/jnumed.112.114298.full.pdf" }
    ],
    related: ["samarium-153-lexidronam", "radium-223", "phosphorus-32", "spect", "bone-metastases"],
    tags: ["bone", "mineral", "palliation"],
  },
  {
    id: "glut-hexokinase",
    kind: "target",
    name: "GLUT1 / hexokinase (glucose metabolism)",
    aka: ["GLUT1", "SLC2A1", "hexokinase II", "HK2"],
    symbol: "SLC2A1",
    tldr: "The two-step system cells use to pull in and lock up glucose for energy. Many cancers rely on this system much more heavily than normal tissue, and a radioactive sugar look-alike called FDG exploits it to light up tumours on a PET scan.",
    summary: "Glucose enters cells through facilitative glucose transporters (GLUTs), of which GLUT1 is the most widely distributed, and is then immediately phosphorylated by hexokinase (chiefly hexokinase II, HK2, in tumours) to glucose-6-phosphate, trapping it inside the cell for glycolysis. Malignant cells characteristically upregulate both GLUT1 and HK2 to sustain the Warburg effect - a high rate of glycolysis even when oxygen is available, driven by oncogenic signalling (PI3K/AKT, MYC, RAS, loss of p53) and by hypoxia acting through HIF-1α, which transcriptionally activates GLUT1 and glycolytic enzymes.\n\n18F-fludeoxyglucose (FDG) is a glucose analogue that is carried into cells by GLUT1 (and GLUT3) exactly as glucose is, and phosphorylated by hexokinase to FDG-6-phosphate; because this metabolite lacks the 2'-hydroxyl group needed for further glycolytic processing and most tumours have low glucose-6-phosphatase activity to reverse the reaction, FDG-6-phosphate becomes metabolically trapped and accumulates in proportion to glycolytic flux. This is read out on PET as the standardised uptake value (SUV), the basis of FDG-PET staging, restaging and treatment response assessment across most solid tumours and lymphomas.\n\nAs a target, GLUT1/hexokinase's strength is near-universal upregulation across a very wide range of cancers, giving FDG-PET its broad utility as a single default oncology tracer. Its central weakness is specificity: any tissue with high glucose demand - brain, myocardium, active skeletal muscle, brown fat, healing wounds, infection and inflammation - also accumulates FDG strongly, so a positive scan requires anatomical and clinical correlation rather than being cancer-specific by itself; hyperglycaemia at the time of injection also competes with FDG uptake and reduces sensitivity.",
    targetClass: "enzyme",
    biology: "Glucose enters cells through facilitative glucose transporters (chiefly GLUT1) and is then phosphorylated by hexokinase (chiefly hexokinase II in tumours), trapping it inside the cell. Cancer cells characteristically upregulate both proteins to sustain high glycolytic flux even in the presence of oxygen (the Warburg effect), which is what the glucose analogue FDG exploits for PET imaging.",
    whereFound: [
      "Most solid tumours and lymphomas: GLUT1 and hexokinase II upregulated in proportion to glycolytic rate, the basis of FDG-PET",
      "Brain (grey matter), myocardium, active skeletal muscle, brown adipose tissue: high physiological glucose uptake, a source of false-positive or confounding FDG signal",
      "Sites of infection and inflammation: activated leukocytes also take up FDG avidly, another source of non-specific uptake"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "PMC: roles of GLUT-1 and HK-II expression in tumour biology and FDG uptake", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6508962/" },
      { label: "PMC: mechanisms underlying FDG uptake in cancer", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5120247/" },
      { label: "StatPearls: fludeoxyglucose (18F) mechanism of action", url: "https://www.ncbi.nlm.nih.gov/books/NBK557653/" },
      { label: "PMC: imaging cancer metabolism, underlying biology and pitfalls of FDG-PET", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6126440/" }
    ],
    related: ["fludeoxyglucose-f18", "fdg-pet", "suv"],
    tags: ["metabolism", "glycolysis", "pan-cancer"],
  },
  {
    id: "integrin-avb3",
    kind: "target",
    name: "Integrin αvβ3",
    aka: ["Integrin alpha-v beta-3", "vitronectin receptor"],
    tldr: "A docking protein on the surface of cells that are building new blood vessels, including the blood vessels a growing tumour needs. Peptides that mimic the docking sequence (RGD) can be radiolabelled to see where this new blood-vessel growth, or the tumour cells themselves, are most active.",
    summary: "Integrin αvβ3 is a heterodimeric transmembrane adhesion receptor that binds extracellular matrix proteins - vitronectin, fibronectin, fibrinogen - through their exposed arginine-glycine-aspartate (RGD) amino acid motif. It is minimally expressed on quiescent, resting blood vessel endothelium but becomes strongly upregulated on activated endothelial cells during angiogenesis, where it is required for the migration, survival and maturation of newly forming vessels, and it is also directly overexpressed on the tumour cells themselves in a range of solid cancers (including glioma, melanoma and some carcinomas), where it promotes invasion and metastasis.\n\nRadiolabelled cyclic RGD peptides (starting with 18F-Galacto-RGD, the first tracer used in patients, and followed by 68Ga-, 64Cu- and 99mTc-labelled RGD monomers, dimers and tetramers) bind αvβ3 and have been used in PET and SPECT imaging as a non-invasive biomarker of tumour angiogenesis, for patient selection ahead of anti-angiogenic therapy and for monitoring treatment response. Multimeric RGD constructs improve binding avidity through a polyvalency effect and show higher, more persistent tumour uptake than monomeric RGD.\n\nAs a target, αvβ3's strength is its sharp induction on angiogenic endothelium, giving genuine biological contrast between growing and quiescent vasculature. Its central weakness for imaging purposes is that αvβ3 is not exclusively expressed on new tumour vessels - it is also present on the tumour cells, on macrophages, and in non-malignant angiogenic settings such as atherosclerotic plaque and post-infarction myocardium - so a static PET signal cannot on its own distinguish tumour-cell expression from vascular expression, and genetic knockout studies suggest angiogenesis can still proceed without αvβ3, which has limited the target's use as a stand-alone therapeutic target despite active imaging interest.",
    targetClass: "surface-antigen",
    biology: "A heterodimeric transmembrane adhesion receptor that binds RGD-motif extracellular matrix proteins such as vitronectin and fibronectin. It is minimally expressed on quiescent blood vessels but strongly upregulated on activated endothelial cells during tumour angiogenesis, and is also directly overexpressed on some tumour cells, where it promotes invasion and migration.",
    whereFound: [
      "Tumour neovasculature (activated endothelial cells during angiogenesis): strongly upregulated versus quiescent vessels",
      "Tumour cells directly in glioma, melanoma and some carcinomas: overexpression linked to invasion and metastasis",
      "Atherosclerotic plaque and post-myocardial-infarction myocardium: upregulated on macrophages and activated endothelium, a non-oncological imaging application",
      "Quiescent normal vasculature: low or absent expression"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "PMC: PET imaging of integrin αvβ3 expression", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3086612/" },
      { label: "PMC: clinical application of radiolabeled RGD peptides for PET imaging of angiogenesis", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4679356/" },
      { label: "PMC: RGD-binding integrins revisited - review of imaging targets including αvβ3", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC8038522/" },
      { label: "PMC: PET radiopharmaceuticals for imaging integrin expression", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC4072020/" }
    ],
    related: [],
    tags: ["angiogenesis", "integrin", "RGD peptide"],
  },
  {
    id: "cck2-receptor",
    kind: "target",
    name: "CCK2 receptor (gastrin receptor)",
    aka: ["CCK2R", "CCK-B receptor", "gastrin receptor"],
    tldr: "A docking site for the hormone gastrin, found at very high numbers on medullary thyroid cancer cells. Minigastrin-like radioactive drugs can bind it to find or treat that cancer, though they also light up the stomach because the same receptor lines it normally.",
    summary: "CCK2R is a G-protein-coupled receptor for the hormones gastrin and cholecystokinin, expressed physiologically in the gastric mucosa where it regulates acid secretion, and in parts of the central nervous system. It is overexpressed at very high incidence and density in medullary thyroid carcinoma (MTC) - historically detected indirectly through the pentagastrin stimulation test - and also occurs in a substantial minority of small-cell lung cancers, astrocytomas, stromal ovarian cancers, gastrointestinal stromal tumours and some gastroenteropancreatic neuroendocrine tumours.\n\nRadiolabelled analogues of minigastrin, which retains the C-terminal receptor-binding tetrapeptide sequence (Trp-Met-Asp-Phe-NH2) common to gastrin and CCK, have been developed for both imaging (111In-, 99mTc-, or 68Ga-labelled minigastrin analogues, including Demogastrin 2 and MGS5) and therapy (90Y- or 177Lu-labelled minigastrin, such as 177Lu-PP-F11N). In patients with metastatic MTC, CCK2R-targeted imaging has detected more lesions than somatostatin receptor imaging, reflecting the low SSTR expression typical of MTC.\n\nAs a target, CCK2R's strength is very high density (over 90% of MTCs) and no competing standard-of-care radiotracer. Its central weakness, which has so far limited therapeutic use, is that the stomach expresses CCK2R physiologically and receives a comparable or higher radiation dose than the tumour with agonist-based minigastrin analogues, making the stomach dose-limiting; kidney and bone-marrow toxicity have also constrained early therapy trials, and receptor antagonist-based ligands (for example those built on nastorazepide) are being explored as an alternative with potentially better tumour-to-stomach ratios.",
    targetClass: "surface-antigen",
    biology: "A G-protein-coupled receptor for gastrin and cholecystokinin that physiologically regulates gastric acid secretion. It is overexpressed at very high density in medullary thyroid carcinoma and in a substantial minority of small-cell lung cancer, astrocytoma and other tumours, providing a target for minigastrin-based radiopeptides.",
    whereFound: [
      "Medullary thyroid carcinoma: expressed at high density in over 90% of cases",
      "Small-cell lung cancer: expressed in roughly half of cases",
      "Astrocytoma, stromal ovarian cancer, gastrointestinal stromal tumours, some gastroenteropancreatic neuroendocrine tumours: variable expression",
      "Normal gastric mucosa: physiological expression, the dose-limiting normal-tissue site for minigastrin therapy"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "PMC: radiolabeled CCK/gastrin peptides for imaging and therapy", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC3205271/" },
      { label: "JNM: CCK2 receptor agonist 177Lu-PP-F11N for medullary thyroid carcinoma therapy - dosimetry", url: "https://jnm.snmjournals.org/content/61/4/520" },
      { label: "PMC: cholecystokinin-2 receptor targeting with radiolabeled peptides (review)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC7116483/" },
      { label: "Theranostics: nastorazepide-based CCK2R antagonist radioligands", url: "https://www.thno.org/v16p8447.htm" }
    ],
    related: ["thyroid", "sclc"],
    tags: ["neuroendocrine", "thyroid", "GPCR"],
  },
  {
    id: "upar",
    kind: "target",
    name: "uPAR (urokinase plasminogen activator receptor)",
    aka: ["uPAR", "PLAUR"],
    symbol: "PLAUR",
    tldr: "A protein that helps cancer cells break through surrounding tissue and spread. Higher amounts on a tumour are linked to more aggressive disease, and a PET tracer built on a small peptide can measure how much of it a tumour has.",
    summary: "uPAR is a glycosylphosphatidylinositol-anchored cell-surface receptor for urokinase-type plasminogen activator (uPA); the uPA/uPAR system focuses proteolytic activity (activation of plasmin, which degrades extracellular matrix) at the cell surface, driving tumour cell invasion, matrix remodelling and metastasis. uPAR overexpression is an established biomarker of tumour aggressiveness across several common cancers, including prostate, breast, bladder and glioma, and correlates with independent prognostic information beyond PSA and Gleason score in prostate cancer.\n\nThe PET ligand 68Ga-NOTA-AE105 (and the earlier 64Cu-DOTA-AE105), based on the high-affinity peptide antagonist AE105, has been evaluated in first-in-human and phase 2 studies in prostate cancer, breast cancer, bladder cancer and glioma. In localised prostate cancer, tumour SUVmax on 68Ga-NOTA-AE105 PET correlated significantly with Gleason score (Spearman ρ = 0.55), and a SUVmax cut-off achieved 96% sensitivity for detecting Gleason score ≥3+4, raising the possibility of uPAR PET reducing the number of repeat biopsies needed in active surveillance. In glioma, uPAR-PET uptake was associated with worse overall and progression-free survival.\n\nAs a target, uPAR's strength is a genuine link to tumour aggressiveness and metastatic potential across multiple tumour types, giving it prognostic as well as localising value. Its main limitation to date is that all published clinical PET data come from small studies run predominantly by one research group, so multicentre validation is still needed, and no uPAR-targeted therapeutic radioligand has reached clinical use.",
    targetClass: "surface-antigen",
    biology: "A GPI-anchored cell-surface receptor for urokinase-type plasminogen activator that focuses proteolytic activity at the cell surface, activating plasmin to degrade extracellular matrix and drive tumour invasion and metastasis. Its overexpression is an established biomarker of tumour aggressiveness in prostate, breast, bladder cancer and glioma.",
    whereFound: [
      "Prostate cancer: uPAR expression correlates with Gleason score and aggressiveness",
      "Glioma: uPAR-PET uptake associated with tumour grade and worse survival",
      "Breast cancer and urinary bladder cancer: uPAR overexpression linked to invasive and metastatic potential",
      "Normal tissue: low background expression, contributing to good image contrast"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "JNM: uPAR PET/MRI (68Ga-NOTA-AE105) and Gleason score correlation in prostate cancer", url: "https://jnm.snmjournals.org/content/62/3/354" },
      { label: "PMC: PET imaging of uPAR in prostate cancer (review)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC5118403/" },
      { label: "JNM: first-in-human study of 68Ga-NOTA-AE105 for uPAR PET imaging", url: "https://jnm.snmjournals.org/content/58/3/379" },
      { label: "EJNMMI Research: phase 2 trial of 68Ga-NOTA-AE105 uPAR PET in glioma, survival correlation", url: "https://ejnmmires.springeropen.com/articles/10.1186/s13550-024-01164-9" }
    ],
    related: ["prostate", "nct06474806"],
    tags: ["invasion", "prostate cancer", "prognostic biomarker"],
  },
  {
    id: "mesothelin",
    kind: "target",
    name: "Mesothelin (MSLN)",
    aka: ["MSLN"],
    symbol: "MSLN",
    tldr: "A protein normally found only on the thin lining of the chest and abdomen, but made in large amounts by mesothelioma and by most pancreatic and many ovarian cancers. Because healthy organs barely make it, it is an attractive handle for antibody-based imaging and treatment.",
    summary: "Mesothelin is a glycosylphosphatidylinositol-anchored cell-surface glycoprotein whose normal expression is restricted to mesothelial cells lining the pleura, pericardium and peritoneum. Its physiological function is not fully established, but it binds CA-125/MUC16, an interaction implicated in the peritoneal spread of ovarian cancer, and its overexpression has been linked to activation of NF-κB, MAPK and PI3K signalling that promotes proliferation, invasion and resistance to apoptosis.\n\nMesothelin is essentially absent from normal pancreas but is expressed in close to 100% of pancreatic ductal adenocarcinomas and virtually all epithelioid (though not sarcomatoid) mesotheliomas, and in a substantial majority of ovarian carcinomas (particularly serous subtype) and roughly half of lung adenocarcinomas, giving a wide tumour-to-normal-tissue contrast that has made it a target for antibody-drug conjugates (for example DMOT4039A/anetumab), immunotoxins (SS1P, LMB-100), CAR-T therapy and radiolabelled antibodies. 89Zr-labelled anti-mesothelin antibody immunoPET (for example 89Zr-MMOT0530A) has visualised pancreatic and ovarian cancer lesions in patients, with higher mean tumour SUVmax in ovarian than pancreatic lesions, plausibly reflecting the dense desmoplastic stroma that limits antibody penetration in pancreatic tumours. A thorium-227-labelled anti-mesothelin antibody-chelator conjugate (BAY2287411) has been tested in a first-in-human alpha-therapy trial in mesothelin-expressing tumours.\n\nAs a target, mesothelin's strength is a genuinely restricted normal-tissue expression pattern combined with near-universal expression in several hard-to-treat cancers. Its main limitations are that, as an antibody target, achieving good tumour penetration in stroma-rich tumours such as pancreatic adenocarcinoma is harder than in mesothelioma or ovarian cancer, and mesothelin is also shed from the cell surface into blood and ascites, which can act as an antigen sink for circulating antibody-based agents.",
    targetClass: "surface-antigen",
    biology: "A GPI-anchored cell-surface glycoprotein normally restricted to mesothelial cells lining the pleura, pericardium and peritoneum, whose interaction with CA-125/MUC16 has been implicated in the peritoneal spread of ovarian cancer. It is overexpressed in nearly all pancreatic ductal adenocarcinomas and epithelioid mesotheliomas and in most serous ovarian carcinomas, while normal organ parenchyma is negative.",
    whereFound: [
      "Malignant pleural mesothelioma (epithelioid subtype): expressed in essentially all cases, absent in sarcomatoid mesothelioma",
      "Pancreatic ductal adenocarcinoma: expressed in close to 100% of cases, absent in normal pancreas and chronic pancreatitis",
      "Ovarian cancer (mainly serous subtype): expressed in roughly 70-100% of cases",
      "Lung adenocarcinoma: expressed in a substantial minority of cases",
      "Normal tissue: limited to mesothelial cells of pleura, pericardium and peritoneum"
    ],
    asOf: "2026-09-22",
    links: [
      { label: "PMC: mesothelin-targeted cancer immunotherapy (expression table across tumour types)", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC2265108/" },
      { label: "PMC: mesothelin as a biomarker for targeted therapy", url: "https://pmc.ncbi.nlm.nih.gov/articles/PMC6708176/" },
      { label: "Clinical Cancer Research: immunoPET with anti-mesothelin antibody (89Zr-MMOT0530A) in pancreatic and ovarian cancer", url: "https://aacrjournals.org/clincancerres/article/22/7/1642/121738/ImmunoPET-with-Anti-Mesothelin-Antibody-in" },
      { label: "MDPI Cancers: mesothelin as an immunotherapeutic target, including BAY2287411 thorium-227 conjugate", url: "https://www.mdpi.com/2072-6694/14/6/1550" }
    ],
    related: [],
    tags: ["mesothelioma", "pancreatic cancer", "ovarian cancer", "antibody target"],
  },
];
