"""Shared vocabulary: isotope signatures, agent/target dictionaries, disease buckets. Used by every harvester."""
import re

# isotope key -> (display, role, regex)
ISO = {
 "Lu-177": ("Lutetium-177", "therapy", r"(?:\b|\[)177\s*\]?\s*-?\s*lu\b|\blu\s*-?\s*177\b|lutetium"),
 "Ac-225": ("Actinium-225", "therapy", r"(?:\b|\[)225\s*\]?\s*-?\s*ac\b|\bac\s*-?\s*225\b|actinium"),
 "Pb-212": ("Lead-212", "therapy", r"(?:\b|\[)212\s*\]?\s*-?\s*pb\b|\bpb\s*-?\s*212\b|lead-212"),
 "Pb-203": ("Lead-203", "diagnostic", r"(?:\b|\[)203\s*\]?\s*-?\s*pb\b|\bpb\s*-?\s*203\b|lead-203"),
 "Th-227": ("Thorium-227", "therapy", r"(?:\b|\[)227\s*\]?\s*-?\s*th\b|\bth\s*-?\s*227\b|thorium"),
 "At-211": ("Astatine-211", "therapy", r"(?:\b|\[)211\s*\]?\s*-?\s*at\b|\bat\s*-?\s*211\b|astatine"),
 "Bi-213": ("Bismuth-213", "therapy", r"(?:\b|\[)213\s*\]?\s*-?\s*bi\b|\bbi\s*-?\s*213\b|bismuth-213"),
 "Ra-223": ("Radium-223", "therapy", r"(?:\b|\[)223\s*\]?\s*-?\s*ra\b|\bra\s*-?\s*223\b|radium-?\s*223|xofigo|radium chloride"),
 "Ra-224": ("Radium-224", "therapy", r"\bra\s*-?\s*224\b|224\s*ra\b|radium-?\s*224"),
 "Tb-161": ("Terbium-161", "therapy", r"(?:\b|\[)161\s*\]?\s*-?\s*tb\b|\btb\s*-?\s*161\b|terbium-?\s*161"),
 "Tb-152": ("Terbium-152", "diagnostic", r"\btb\s*-?\s*152\b|152\s*tb\b"),
 "Cu-67": ("Copper-67", "therapy", r"(?:\b|\[)67\s*\]?\s*-?\s*cu\b|\bcu\s*-?\s*67\b|copper-?\s*67"),
 "Cu-64": ("Copper-64", "diagnostic", r"(?:\b|\[)64\s*\]?\s*-?\s*cu\b|\bcu\s*-?\s*64\b|copper-?\s*64|detectnet"),
 "Cu-61": ("Copper-61", "diagnostic", r"\bcu\s*-?\s*61\b|61\s*cu\b"),
 "Y-90": ("Yttrium-90", "therapy", r"(?:\b|\[)90\s*\]?\s*-?\s*y\b|\by\s*-?\s*90\b|yttrium|sir-?spheres|therasphere|zevalin"),
 "Y-86": ("Yttrium-86", "diagnostic", r"\by\s*-?\s*86\b|86\s*y\b"),
 "I-131": ("Iodine-131", "therapy", r"(?:\b|\[)131\s*\]?\s*-?\s*i\b|\bi\s*-?\s*131\b|iodine-?\s*131|radioiodine|radioactive iodine|sodium iodide i|azedra|iomab|iopofosine|clr\s*131|131i-"),
 "I-123": ("Iodine-123", "diagnostic", r"(?:\b|\[)123\s*\]?\s*-?\s*i\b|\bi\s*-?\s*123\b|iodine-?\s*123|ioflupane|datscan|adreview"),
 "I-124": ("Iodine-124", "diagnostic", r"(?:\b|\[)124\s*\]?\s*-?\s*i\b|\bi\s*-?\s*124\b|iodine-?\s*124"),
 "I-125": ("Iodine-125", "therapy", r"(?:\b|\[)125\s*\]?\s*-?\s*i\b|\bi\s*-?\s*125\b|iodine-?\s*125"),
 "Ga-68": ("Gallium-68", "diagnostic", r"(?:\b|\[)68\s*\]?\s*-?\s*ga\b|\bga\s*-?\s*68\b|gallium-?\s*68|netspot|locametz|illuccix|gozellix|gozetotide"),
 "Ga-67": ("Gallium-67", "diagnostic", r"\bga\s*-?\s*67\b|67\s*ga\b|gallium citrate|gallium-?\s*67"),
 "F-18": ("Fluorine-18", "diagnostic", r"(?:\b|\[)18\s*\]?\s*-?\s*f\b|\bf\s*-?\s*18\b|fluorine-?\s*18|\bfdg\b|fludeoxyglucose|fluorodeoxyglucose|fluciclovine|axumin|piflufolastat|pylarify|flotufolastat|posluma|florbetapir|amyvid|flutemetamol|vizamyl|florbetaben|neuraceq|flortaucipir|tauvid|fluoroestradiol|cerianna|fluorodopa|fdopa|f-dopa|flurpiridaz|flyrcado|fluorocholine|fluoromisonidazole|fmiso|\bfaza\b|fluorothymidine|\bflt\b|\bfet\b|fluoroethyl|sodium fluoride|\bnaf\b|mk-?6240|pi-?2620|\bfes\b|dcfpyl|psma-1007|\bapn-?1607|\bflurpiridaz"),
 "Zr-89": ("Zirconium-89", "diagnostic", r"(?:\b|\[)89\s*\]?\s*-?\s*zr\b|\bzr\s*-?\s*89\b|zirconium|zircaix|tlx250-cdx"),
 "Tc-99m": ("Technetium-99m", "diagnostic", r"99m\s*-?\s*tc\b|\btc\s*-?\s*99m?\b|technetium|sestamibi|cardiolite|tetrofosmin|myoview|tilmanocept|lymphoseek|mertiatide|mag3|\bdmsa\b|\bhmpao\b|exametazime|bicisate|medronate|\bmdp\b|\bhdp\b|oxidronate|pyrophosphate|\bpyp\b|sulfur colloid|\bmaa\b|macroaggregated|technegas|\bdtpa\b|pentetate|mebrofenin|disofenin|sestamibi|trodat|tektrotyd|\bhynic"),
 "In-111": ("Indium-111", "diagnostic", r"(?:\b|\[)111\s*\]?\s*-?\s*in\b|\bin\s*-?\s*111\b|indium|octreoscan|pentetreotide|prostascint|capromab"),
 "Tl-201": ("Thallium-201", "diagnostic", r"\btl\s*-?\s*201\b|201\s*tl\b|thallium"),
 "Rb-82": ("Rubidium-82", "diagnostic", r"\brb\s*-?\s*82\b|82\s*rb\b|rubidium|cardiogen|ruby-?fill"),
 "N-13": ("Nitrogen-13", "diagnostic", r"\bn\s*-?\s*13\b|13\s*n\s*-?\s*ammonia|nitrogen-?\s*13|ammonia n\s*13|13n-ammonia"),
 "O-15": ("Oxygen-15", "diagnostic", r"\bo\s*-?\s*15\b|15\s*o\b|oxygen-?\s*15|h2\s*15\s*o|\[15o\]"),
 "C-11": ("Carbon-11", "diagnostic", r"(?:\b|\[)11\s*\]?\s*-?\s*c\b|\bc\s*-?\s*11\b|carbon-?\s*11|\bpib\b|pittsburgh compound|choline c\s*11|raclopride|ucb-?j|pbr28|\bpk11195"),
 "Sc-44": ("Scandium-44", "diagnostic", r"\bsc\s*-?\s*44\b|44\s*sc\b"),
 "Sc-47": ("Scandium-47", "therapy", r"\bsc\s*-?\s*47\b|47\s*sc\b"),
 "Ho-166": ("Holmium-166", "therapy", r"\bho\s*-?\s*166\b|166\s*ho\b|holmium|quiremspheres"),
 "Re-188": ("Rhenium-188", "therapy", r"\bre\s*-?\s*188\b|188\s*re\b|rhenium-?\s*188"),
 "Re-186": ("Rhenium-186", "therapy", r"\bre\s*-?\s*186\b|186\s*re\b|rhenium-?\s*186"),
 "Sm-153": ("Samarium-153", "therapy", r"\bsm\s*-?\s*153\b|153\s*sm\b|samarium|quadramet"),
 "Sr-89": ("Strontium-89", "therapy", r"\bsr\s*-?\s*89\b|89\s*sr\b|strontium-?\s*89|metastron"),
 "P-32": ("Phosphorus-32", "therapy", r"\bp\s*-?\s*32\b|32\s*p\b|phosphorus-?\s*32|oncosil"),
 "Xe-133": ("Xenon-133", "diagnostic", r"\bxe\s*-?\s*133\b|133\s*xe\b|xenon-?\s*133"),
 "Kr-81m": ("Krypton-81m", "diagnostic", r"\bkr\s*-?\s*81m?\b|81m\s*kr\b|krypton"),
 "Er-169": ("Erbium-169", "therapy", r"\ber\s*-?\s*169\b|169\s*er\b|erbium"),
 "Sn-117m": ("Tin-117m", "therapy", r"117m\s*sn\b|\bsn\s*-?\s*117m\b|tin-?\s*117m"),
 "Cr-51": ("Chromium-51", "diagnostic", r"\bcr\s*-?\s*51\b|51\s*cr\b|chromium-?\s*51"),
}
ISO_RE = {k: re.compile(v[2], re.I) for k, v in ISO.items()}

# Class words that on their own mark a radiopharmaceutical intervention (used with an isotope or a known agent)
CLASS_RE = re.compile(r"radioligand|radiopharmaceutical|radionuclide|radiotracer|radiolabel|radioimmuno|radioemboli|\bsirt\b|\bprrt\b|theranostic|targeted alpha|alpha-?emitter|immuno-?pet|radioguided|radiosynov|scintigraph|\bspect\b|\bpet\b|pet/ct|pet-ct|pet/mr", re.I)

# target key -> regex over agent/intervention text
TARGETS = {
 "psma": r"psma|prostate-specific membrane|vipivotide|pluvicto|gozetotide|piflufolastat|flotufolastat|dcfpyl|pylarify|posluma|locametz|illuccix|gozellix|i&t|\bpsma-?617|rosopatamab|j591|tlx591|pnt2002|mip-?1095|capromab|prostascint|\bpsma-?11|rhpsma|ludotadipep|\balb-?psma|ga-?68-?p16-?093|p16-?093|psma-?1007|ctt1403|fpi-?2265|aaa817",
 "sstr": r"sstr|somatostatin|dotatate|dotatoc|dotanoc|edotreotide|oxodotreotide|lutathera|netspot|detectnet|octreotide|octreoscan|pentetreotide|satoreotide|jr11|\blm3\b|ope\s*-?\s*mod|itm-?11|ryz101|tektrotyd|\bsso1[12]0|dotaexendin",
 "fap": r"\bfap\b|fapi|fibroblast activation|fap-?2286|opi-?\d|\bfap-?\d|sofie|\bfapi-?\d+|3bp-?\d+|lnc1004|ptfap",
 "grpr": r"grpr|bombesin|gastrin-releasing|\brm2\b|rm26|\bneob\b|neobomb|ampro|sarcobombesin|\bbbn",
 "cxcr4": r"cxcr4|pentixafor|pentixather|mb-?4 cxcr4",
 "her2": r"her2|erbb2|trastuzumab|pertuzumab|anti-?her2 nanobody",
 "caix": r"caix|ca9\b|carbonic anhydrase ix|girentuximab|tlx250|zircaix|dpi-?4452",
 "cd20": r"\bcd20\b|ibritumomab|zevalin|rituximab|tositumomab|bexxar",
 "cd45": r"\bcd45\b|apamistamab|iomab",
 "cd37": r"\bcd37\b|lilotomab|betalutin",
 "cd38": r"\bcd38\b|daratumumab pet|89zr-?dfo-?daratumumab",
 "gd2": r"\bgd2\b|dinutuximab|3f8|naxitamab",
 "b7-h3": r"b7-?h3|omburtamab|8h9",
 "dll3": r"dll3|delta-?like ligand 3|sc16",
 "nectin-4": r"nectin-?4|n188",
 "trop2": r"trop-?2|trop2|sacituzumab|datopotamab",
 "ceacam5": r"ceacam5|\bcea\b|carcinoembryonic|arcitumomab|sgm-?101|labetuzumab|tf2",
 "cldn18-2": r"cldn18|claudin",
 "gpc3": r"gpc3|glypican",
 "integrin": r"integrin|\brgd\b|alpha-?v-?beta|avb[36]|fluciclatide|alfatide|prgd2|3prgd2",
 "ntsr1": r"ntsr1|neurotensin|3bp-?227",
 "cck2r": r"cck2|cck-?2|minigastrin|gastrin receptor|ctr-?\d|pp-?f11",
 "glp1r": r"glp-?1r|exendin|glp-?1 receptor|insulinoma imaging",
 "mc1r": r"mc1r|melanocortin|\bmsh\b",
 "pd-l1": r"pd-?l1|atezolizumab pet|durvalumab pet|bms-?986192|wl12",
 "pd-1": r"\bpd-?1\b|nivolumab pet|pembrolizumab pet",
 "cd8": r"\bcd8\b|crefmirlimab|zed88082a",
 "granzyme-b": r"granzyme",
 "egfr": r"\begfr\b|cetuximab|panitumumab",
 "her3": r"her3|erbb3|patritumab",
 "mesothelin": r"mesothelin",
 "cd70": r"\bcd70\b",
 "cd33": r"\bcd33\b|lintuzumab",
 "cd123": r"cd123",
 "mucin": r"muc1|muc16|ca-?125|ca125",
 "5t4": r"\b5t4\b|tpbg",
 "sortilin": r"sortilin|sort1",
 "b1r": r"bradykinin|\bb1r\b",
 "psca": r"\bpsca\b",
 "steap1": r"steap",
 "klk2": r"hk2\b|klk2|kallikrein",
 "pars": r"\bpar-?[12]\b",
 "amyloid": r"(?<!cardiac )(?<!light-chain )(?<!\bal )(?<!attr )(?<!transthyretin )amyloid(?!osis)(?! light)|β-amyloid|florbetapir|amyvid|flutemetamol|vizamyl|florbetaben|neuraceq|\bpib\b|pittsburgh|nav4694|flutafuranol",
 "tau": r"\btau\b|flortaucipir|tauvid|mk-?6240|pi-?2620|ro-?948|apn-?1607|genentech tau|\bpm-?pbb3",
 "alpha-synuclein": r"synuclein|aci-?12589",
 "dat": r"dopamine transporter|\bdat\b|ioflupane|datscan|fp-?cit|trodat|pe2i|altropane|fe-?pe2i",
 "vmat2": r"vmat2|dtbz|dihydrotetrabenazine|av-?133",
 "net-transporter": r"norepinephrine transporter|mibg|iobenguane|azedra|adreview|mfbg|lmi1195|flubrobenguane",
 "tspo": r"\btspo\b|translocator protein|pbr28|pk11195|dpa-?714|ge-?180|er176",
 "sv2a": r"sv2a|ucb-?j|ucb-?h|synaptic vesicle",
 "mglur5": r"mglur5|abp688|fpeb",
 "estrogen-receptor": r"estrogen receptor|oestrogen receptor|fluoroestradiol|\bfes\b|cerianna|4fmfes",
 "androgen-receptor": r"androgen receptor|\bfdht\b|dihydrotestosterone",
 "progesterone-receptor": r"progesterone receptor|ffnp",
 "glucose-metabolism": r"\bfdg\b|fludeoxyglucose|fluorodeoxyglucose",
 "amino-acid-transport": r"fluciclovine|axumin|methionine|\bfet\b|fluoroethyl-?l?-?tyrosine|fluorodopa|fdopa|f-dopa|glutamine|\bfaci\b|\bfsp[gG]",
 "hypoxia": r"hypoxia|fmiso|fluoromisonidazole|\bfaza\b|cu-?atsm|atsm|hx4|ef5",
 "proliferation": r"fluorothymidine|\bflt\b|cellular proliferation",
 "bone-mineral": r"sodium fluoride|\bnaf\b|medronate|\bmdp\b|\bhdp\b|oxidronate|bone scan|radium|samarium|strontium|metastron|quadramet|xofigo|zoledron",
 "myocardial-perfusion": r"sestamibi|cardiolite|tetrofosmin|myoview|flurpiridaz|flyrcado|rubidium|\brb-?82|ammonia|thallium|myocardial perfusion|water pet|15o-?water",
 "choline-metabolism": r"(?<!acetyl)(?<!butyryl)choline(?!rg|st)",
 "psma-negative-lipid": r"(?:11\s?c|c-?11|carbon-11)\]?[- ]?acetate|acetate[- ]pet",
 "parp": r"\bparp|ftt\b|parpi|olaparib pet|\b18f-?ftt",
 "fibrin": r"fibrin|\bep-?2104|thrombus imaging",
 "collagen": r"collagen|cbp8",
 "cxcr2": r"cxcr2",
 "ccr2": r"ccr2",
 "insulin-like": r"igf-?1r",
 "c-met": r"c-?met\b|hgfr",
 "vegf": r"bevacizumab pet|\bvegf",
 "lymphatic-mapping": r"tilmanocept|lymphoseek|sulfur colloid|sentinel|nanocolloid|lymphoscintigraph",
 "renal-function": r"mag3|mertiatide|\bdtpa\b|pentetate|\bdmsa\b|renogra",
 "perfusion-ventilation": r"\bmaa\b|macroaggregated|technegas|xenon|krypton|ventilation|perfusion lung|v/q",
 "hepatobiliary": r"mebrofenin|disofenin|hida|hepatobiliary",
 "cerebral-perfusion": r"hmpao|exametazime|bicisate|\becd\b|cerebral perfusion",
 "infection-inflammation": r"leukocyte|white blood cell|\bwbc\b|gallium citrate|fdg.*infection|infection imaging|bacteria|sorbitol|maltose|trimethoprim pet|\bfdc\b|\bpet.*bacter",
 "cardiac-amyloid": r"pyrophosphate|\bpyp\b|\bdpd\b|hmdp|cardiac amyloid|transthyretin|\battr\b|attr-?cm|attrwt",
 "thyroid": r"(?<!para)thyroid|radioiodine|sodium iodide|pertechnetate",
 "parathyroid": r"parathyroid|sestamibi.*parathyroid|fluorocholine",
 "red-cell": r"red blood cell|rbc scintigraphy|gastrointestinal bleed",
}

# added 24 Sep 2026: public targets (incl. DLG4/PSD-95) the universe build must cover
TARGETS.update({
 "dlg4": r"\bdlg4\b|psd-?95|postsynaptic density protein[- ]95",
 "folate-receptor": r"folate receptor|\bfr-?α|\bfr-?alpha|folr1|etarfolatide|folcepri|farletuzumab|mirvetuximab",
 "cd46": r"\bcd46\b",
 "upar": r"\bupar\b|urokinase[- ]type plasminogen activator receptor|urokinase plasminogen activator receptor",
 "epha2": r"\bepha2\b|ephrin type-a receptor 2",
 "tissue-factor": r"tissue factor\b|tisotumab",
 "l1cam": r"\bl1-?cam\b",
 "gpa33": r"\bgpa33\b|\bhua33\b",
 "cdh6": r"\bcdh6\b|cadherin[- ]6\b",
 "bcma": r"\bbcma\b|b-cell maturation antigen",
 "p2x7": r"\bp2x7",
 "csf1r": r"csf-?1r\b|colony[- ]stimulating factor[- ]1 receptor",
 "sigma-receptor": r"sigma-?[12] receptor|σ[12] receptor|sigma receptor",
 "cb2": r"cannabinoid (?:type )?2 receptor|\bcb2 receptor|\bcb2r\b",
 "adenosine-a2a": r"adenosine a2a|\ba2a receptor|\ba2ar\b",
 "dopamine-d2d3": r"\bd2/d3\b|dopamine d[23] receptor|\bd2 receptor|raclopride|fallypride|\bphno\b",
 "serotonin": r"5-ht(?:1a|2a|4|6|7)\b|serotonin (?:1a|2a|4|transporter)|\bsert\b|\bdasb\b",
 "mao-b": r"\bmao-?b\b|monoamine oxidase[- ]b|deprenyl|\bsmbt-1\b",
 "pde10a": r"\bpde10a?\b",
 "nachr": r"nicotinic acetylcholine|\bnachr\b|flubatine|nifene",
 "gaba-a": r"gaba-?a receptor|flumazenil|benzodiazepine receptor",
 "opioid": r"opioid receptor|carfentanil|diprenorphine",
 "hdac": r"\bhdac\b|histone deacetylase|martinostat",
 "trem2": r"\btrem2\b",
 "cd47": r"\bcd47\b",
 "lag3": r"\blag-?3\b",
 "tigit": r"\btigit\b",
 "ox40": r"\box40\b|\bcd134\b",
 "cd3-cd4-tcell": r"\bcd3\b|\bcd4\b|t[- ]cell imaging",
 "il2": r"interleukin-?2\b|\bil-?2\b",
 "vap1-siglec9": r"\bvap-?1\b|vascular adhesion protein|siglec-?9",
 "mmp": r"matrix metalloproteinase|\bmmp-?\d+\b",
 "npy-y1": r"neuropeptide y\b|\bnpy\b|\by1 receptor",
 "vpac": r"\bvpac|vasoactive intestinal peptide receptor",
 "neurokinin-1": r"neurokinin[- ]1|\bnk1r?\b|substance p\b",
 "apoptosis": r"annexin|caspase-3|apoptosis imaging",
 "cyp11b": r"cyp11b|metomidate|aldosterone synthase",
})
TARGET_RE = {k: re.compile(v, re.I) for k, v in TARGETS.items()}

# disease bucket -> regex over conditions + title
DISEASES = {
 "prostate-cancer": r"prostat",
 "neuroendocrine-tumours": r"neuroendocrine|carcinoid|\bgep-?nets?\b|\bpnets?\b|\bsi-?nets?\b|pancreatic nets?|\bnets\b|\bnens?\b|paraganglioma|pheochromocytoma|phaeochromocytoma|insulinoma|medullary thyroid",
 "neuroblastoma": r"neuroblastoma",
 "thyroid-cancer": r"thyroid (?:cancer|carcinoma|neoplasm)|differentiated thyroid|papillary thyroid|follicular thyroid",
 "breast-cancer": r"breast",
 "lung-cancer": r"lung cancer|lung carcinoma|nsclc|non-small|small cell lung|\bsclc\b|lung neoplasm|pulmonary nodule|mesothelioma",
 "colorectal-cancer": r"colorectal|colon cancer|rectal cancer|colon carcinoma|rectal carcinoma|bowel cancer",
 "liver-cancer": r"hepatocellular|\bhcc\b|liver cancer|liver metast|cholangio|biliary tract|gall ?bladder (?:cancer|carcinoma)",
 "pancreatic-cancer": r"pancrea(?:tic|s) (?:cancer|adenocarcinoma|ductal)|\bpdac\b",
 "gastric-oesophageal-cancer": r"gastric (?:cancer|carcinoma|adenocarcinoma|tumou?r|neoplasm|malignan)|stomach (?:cancer|neoplasm|carcinoma)|esophag\w* (?:cancer|carcinoma|adenocarcinoma|squamous|neoplasm|tumou?r)|gastro-?o?esophageal junction|\bgist\b|gastrointestinal stromal|signet ring",
 "renal-cell-carcinoma": r"renal cell|kidney cancer|renal mass|renal tumou?r|clear cell renal",
 "urothelial-cancer": r"urothelial|(?<!gall)(?<!gall )bladder (?:cancer|carcinoma|tumou?r|neoplasm|malignanc)|\bn?mibc\b|\butuc\b|transitional cell carcinoma|upper tract urothelial",
 "ovarian-gynae-cancer": r"\bovar(?:y|ies|ian)|cervical cancer|cervix|endometri|uterine|gynecolog|gynaecolog",
 "head-neck-cancer": r"head and neck|oropharyn|nasopharyn|laryn|oral cavity|squamous cell carcinoma of the head",
 "brain-tumours": r"(?<!gan)glioma|glioblastoma|brain tumou?r|brain metast|meningioma|astrocytoma|ependymoma|dipg|medulloblastoma",
 "lymphoma": r"lymphoma|hodgkin|dlbcl",
 "leukaemia-myeloma": r"leuk(?:a)?emia|myeloma|myelodysplastic|\baml\b|lymphoblastic|stem cell transplant|h(?:a)?ematopoietic (?:stem )?cell transplant|\bhsct\b",
 "melanoma-skin": r"melanoma|merkel|skin cancer",
 "sarcoma-bone-tumours": r"sarcoma|osteosarcoma|ewing|bone metast|skeletal metast|bone tumou?r|desmoid",
 "paediatric-cancer": r"pediatric|paediatric|child|infant|wilms|retinoblastoma",
 "solid-tumours-general": r"solid tumou?r|advanced cancer|metastatic cancer|neoplasms?$|carcinoma$|cancer$|oncology",
 "alzheimers-dementia": r"alzheimer|dementia|cognitive impairment|(?<!cardiac )amyloid[- ]?(?:pet|β|beta|plaque|imaging|positiv|burden|deposition|negativ)|β-amyloid|beta-amyloid|\bpib\b|florbetapir|florbetaben|flutemetamol",
 "parkinsons-movement": r"parkinson|lewy|multiple system atrophy|progressive supranuclear|corticobasal|huntington|movement disorder|essential tremor",
 "epilepsy": r"epilep|seizure",
 "psychiatry-neuro-other": r"depressive|major depression|depression and anxiety|treatment-resistant depression|late-life depression|\bmdd\b|schizophren|bipolar|autism|addiction|alcohol use|opioid use|substance use|nicotin|tobacco use|ptsd|stroke|multiple sclerosis|\bals\b|amyotrophic|traumatic brain|concussion|chronic pain|neuropathic pain|migraine|fibromyalgia",
 "coronary-heart-disease": r"coronary|myocardial ischemia|myocardial ischaemia|angina|myocardial infarction|chest pain|ischemic heart|ischaemic heart|coronary microvascular|microvascular dysfunction",
 "heart-failure-cardiomyopathy": r"heart failure|cardiomyopathy|cardiac amyloid|transthyretin|\battr\b|attr-?cm|attrwt|cardiac sarcoid|myocarditis|cardiotoxic|cardio-oncology",
 "vascular-thrombosis": r"atheroscler|carotid|(?<!para-)(?<!para)(?<!peri)aortic|aneurysm|vasculitis|arteritis|thrombos|thrombus|thromboemb|embolism|peripheral arter|vulnerable plaque|coronary plaque|carotid plaque",
 "infection": r"infection|infectious|osteomyelitis|endocarditis|tuberculosis|fever of unknown|\bfuo\b|prosthetic joint|sepsis|covid|bacteremia|fungal",
 "inflammation-autoimmune": r"arthritis|inflammatory (?:disease|bowel|arthritis|disorder|condition)|chronic inflammation|neuroinflammation|lupus|crohn|colitis|\bibd\b|sarcoidosis|spondyl|psoria|fibrosis|fibrotic|igg4|polymyalgia|vasculitis",
 "endocrine-metabolic": r"diabetes|diabetic|obesity|adrenal|aldosteron|cushing|hyperparathyroid|parathyroid|hyperinsulin|brown adipose|nafld|\bnash\b|masld|metabolic syndrome|metabolic (?:disease|disorder)|graves|hyperthyroid|toxic nodul|goit",
 "renal-urological": r"kidney disease|\bckd\b|renal transplant|kidney transplant|hydroneph|urinary obstruct|ureteral obstruct|ureteropelvic|obstructive uropathy|vesico-?ureteral reflux|reflux nephropathy|urinary tract infection|urinary tract obstruct|pyelonephritis|renal scar",
 "pulmonary": r"pulmonary embol|copd|asthma|lung transplant|interstitial lung|pulmonary fibrosis|pulmonary hypertension",
 "gastrointestinal": r"gastroparesis|gastric emptying|gastrointestinal bleed|\bgi bleed|meckel|bile leak|biliary atresia|cholecystitis|biliary dyskinesia|cirrhosis|liver disease|hepatic steatosis|liver fibrosis",
}
DISEASE_RE = {k: re.compile(v, re.I) for k, v in DISEASES.items()}

def isotopes_in(text):
    return sorted({k for k, r in ISO_RE.items() if r.search(text)})

def targets_in(text):
    return sorted({k for k, r in TARGET_RE.items() if r.search(text)})

def diseases_in(text):
    out = sorted({k for k, r in DISEASE_RE.items() if r.search(text)})
    if len(out) > 1 and "solid-tumours-general" in out: out.remove("solid-tumours-general")
    return out

def role_of(isos):
    roles = {ISO[i][1] for i in isos}
    if roles == {"therapy"}: return "therapy"
    if roles == {"diagnostic"}: return "diagnostic"
    if roles: return "theranostic"
    return "unknown"
